---
- hosts: all
  user: vagrant
  sudo: yes
  roles:
    - common
  vars:
    work_dir: /home/vagrant
    repos_dir: "{{ work_dir }}/harmox"
    branch: master
  tasks:
    - name: start and enable nginx
      service: name=nginx state=started enabled=yes
    - name: clone harmox-app
      git: repo=git@github.com:pollseed/harmox-app.git dest={{ repos_dir }} version={{ branch }} accept_hostkey=yes key_file=/Users/shn/workspace/harmox/harmox-infra/infra-filling/vagrant/.vagrant/machines/default/virtualbox/private_key
      sudo: false
