Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.network "forwarded_port", guest: 22, host: 2230, auto_correct: true
  config.vm.network "forwarded_port", guest: 80, host: 8888, auto_correct: true
  config.vm.network "public_network", bridge: 'en0: Wi-Fi (AirPort)'
  config.vm.boot_timeout = 100
  config.vm.provider "virtualbox" do |v|
    v.customize ["modifyvm", :id, "--ostype", "Ubuntu_64"]
  end
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
  end
end
